import Head from 'next/head'
import Layout from '@/layout'
import { useSession } from 'next-auth/react'
export default function Home() {

  const {data,status} =  useSession()


  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     <Layout>
      <div>This is Home Ellements</div>
     </Layout>
    </>
  )
}
