import ProductListing from "@/components/searchPage";
import BodySection from "@/components/searchPage/Bodysection";
import FilterSection from "@/components/searchPage/Topsection";
import Layout from "@/layout";
import { Box } from "@mui/material";
import Head from "next/head";
import React from "react";

const Search = () => {
  return (
    <Layout>
    <Head>
        <title>Search Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     <ProductListing/>
    </Layout>
  );
};

export default Search;
