import { ArrayData } from "@/assets/mock/product";
import CartItem from "@/components/elements/CartItem";
import CartRight from "@/components/elements/cartRight";
import Layout from "@/layout";
import {
  Add,
  AddCircleOutline,
  Close,
  Remove,
  RemoveCircleOutline,
} from "@mui/icons-material";
import {
  Box,
  Button,
  Grid,
  IconButton,
  Paper,
  Stack,
  Typography,
  colors,
} from "@mui/material";
import Head from "next/head";
import Image from "next/image";
import { Fragment } from "react";
import { useSelector } from "react-redux";

const CartPage = () => {
  const cartData = useSelector((state) => state["data"].cartItems);
  const wishlist = useSelector((state) => state["data"].wishList);
  return (
    <Fragment>
      <Head>
        <title>Cart Next Ecommerce</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Box p={3} component={"div"}>
          <Typography variant="h1" mb={5}>
            {" "}
            Your Cart
          </Typography>
          <Grid container direction={"row"} gap={5}>
            {cartData.length !== 0 ? (
              <Stack direction={"column"} gap={1.5} flex={2}>
                {cartData?.map((item) => (
                  <CartItem key={item} data={item} />
                ))}
              </Stack>
            ) : (
              <Stack direction={"column"} gap={1.5} flex={2}>
                Cart is empty
              </Stack>
            )}
            <Stack direction={"column"} gap={1} flex={0.9}>
              <CartRight />
            </Stack>
          </Grid>
        </Box>
      </Layout>
    </Fragment>
  );
};

export default CartPage;
