import Info from "@/components/products/Productdetails/Info";
import Related from "@/components/products/Productdetails/Related";
import ProductDetails from "@/components/products/Productdetails/details";
import Layout from "@/layout";
import { Box } from "@mui/material";
import Head from "next/head";
import React from "react";

const Index = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Box p={3} component={"div"}>
          <Info />
          <ProductDetails />
          <Related />
        </Box>
      </Layout>
    </>
  );
};

export default Index;




export async function getServerSideProps(ctx){


  return {
    props:{
      data:null
    }
  }
}