/* eslint-disable react-hooks/exhaustive-deps */
import ProductListing from "@/components/searchPage";
import { useAuthContext } from "@/context/AuthContext";
import Layout from "@/layout";
import Head from "next/head";
import { useEffect } from "react";

const Index = () => {
  return (
    <Layout>
      <Head>
        <title>Search Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ProductListing />
    </Layout>
  );
};

export default Index;
