import { Inter } from "next/font/google";
import "./globals.css";
// import 'resuit/dist/resuit.css';
import { ProviderTheme } from '../utils/ProviderTheme'
import NextAuthProvider from "@/context/sessionContext";
// import { AuthContextProvider } from "@/context/authContext";



const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <NextAuthProvider>
      <html lang="en" suppressHydrationWarning={true}>
        <head>
        <link rel="icon" href="./fivecon.ico" sizes="any" />
        </head>

        <body className={inter.className}>

          <ProviderTheme>

            {children}
          </ProviderTheme>
        </body>
      </html></NextAuthProvider>
  );
}
