import { Inter } from "next/font/google";
import "./globals.css";
import { ProviderTheme } from '../utils/ProviderTheme'
import NextAuthProvider from "@/context/sessionContext";
import { Provider } from 'react-redux'
import { store } from "@/store";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <NextAuthProvider>
      <html lang="en" suppressHydrationWarning>
        {/* <Provider store={store}>



        </Provider> */}

        
<body className={inter.className}>

<ProviderTheme>
  {children}
</ProviderTheme>
</body>
      </html></NextAuthProvider>
  );
}
