import { allproducts, productData } from "@/assets/mock/product";
import Info from "@/components/products/Productdetails/Info";
import Related from "@/components/products/Productdetails/Related";
import ProductDetails from "@/components/products/Productdetails/details";
import Layout from "@/layout";
import { apiUrl } from "@/utils/config";
import { Box } from "@mui/material";
import Head from "next/head";
import { useParams } from "next/navigation";
import React from "react";

const Index = () => {
  const data = allproducts;
  const params = useParams();

  const product = data.find((data) => data.slug === params?.["productId"]);
  const relatedProduct = data;
  console.log(product);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Box p={3} component={"div"}>
          {/* <Info data={product} />
          <ProductDetails data={product} />
          <Related data={relatedProduct} /> */}
        </Box>
      </Layout>
    </>
  );
};

export default Index;

export const getServerSideProps = async (ctx) => {
  // const id = ctx.params["productId"];
  // const path = { slug: ctx.params["productId"] };
  // const resData = await fetch(
  //   `${apiUrl}/products/slag:${JSON.stringify(path)}`
  // );
  // const cate = await resData.json();

  // console.log(cate);
  // return {
  //   props: {
  //     cate,
  //   },
  // };
};
